import bcrypt from 'bcryptjs';

interface InitialProducts {
  description: string;
  images: string[];
  inStock: number;
  price: number;
  sizes: ValidSizes[];
  slug: string;
  type: ValidTypes;
  tags: string[];
  title: string;
  gender: 'men' | 'women' | 'girls' | 'boys';
}
type ValidTypes = 'clothing' | 'shoes';
type ClothesAdultsSizes = 'XS' | 'S' | 'M' | 'L' | 'XL';
type ClothesBoysSizes =
  | '2 years'
  | '3 years'
  | '4 years'
  | '5 years'
  | '5-6 years'
  | '7-8 years'
  | '9-10 years'
  | '11-12 years'
  | '13-14 years'
  | '15-16 years';
type ShoesAdultsSizes =
  | '5'
  | '5.5'
  | '6'
  | '6.5'
  | '7'
  | '7.5'
  | '8'
  | '8.5'
  | '9'
  | '9.5'
  | '10'
  | '10.5'
  | '11'
  | '11.5'
  | '12'
  | '12.5'
  | '13'
  | '13.5'
  | '14';
type ShoesKidsSizes =
  | '1k'
  | '2k'
  | '3k'
  | '4k'
  | '5k'
  | '5.5k'
  | '6k'
  | '6.5k'
  | '7k'
  | '7.5k'
  | '8k'
  | '8.5k'
  | '9k'
  | '9.5k'
  | '10k'
  | '10.5k'
  | '11k'
  | '11.5k'
  | '12k'
  | '12.5k'
  | '13k'
  | '13.5k'
  | '1'
  | '1.5'
  | '2'
  | '2.5'
  | '3'
  | '3.5'
  | '4'
  | '4.5';
type ValidSizes =
  | ClothesBoysSizes
  | ClothesAdultsSizes
  | ShoesAdultsSizes
  | ShoesKidsSizes;

interface SeedUser {
  name: string;
  email: string;
  password: string;
  role: 'admin' | 'client';
}

interface InitialData {
  users: SeedUser[];
  products: InitialProducts[];
}

export const initialData: InitialData = {
  users: [
    {
      name: 'Ricardo Flores',
      email: 'rfjiq1986@gmail.com',
      password: bcrypt.hashSync('123456'),
      role: 'admin',
    },
    {
      name: 'Billy the kiii',
      email: 'billy@gmail.com',
      password: bcrypt.hashSync('123456'),
      role: 'client',
    },
  ],
  products: [
    {
      description:
        'Pants de futbol absorbentes hechos con materiales reciclados. Hecho con materiales 100% reciclados, este producto representa solo una de nuestras soluciones para acabar con los residuos',
      images: [
        'tiro_essential_pants_women_01.jpg',
        'tiro_essential_pants_women_02.jpg',
        'tiro_essential_pants_women_03.jpg',
      ],
      inStock: 30,
      price: 47.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'tiro_essential_pants_women',
      type: 'clothing',
      tags: ['pants'],
      title: 'Tiro Essential Pants',
      gender: 'women',
    },
    {
      description:
        'Shorts creados con marimekko, hechos parcialmente con parley ocean plastic. Esta prenda está confeccionada con hilo que contiene un 50% de Parley Ocean Plastic, un material que ha sido recuperado de residuos plásticos recogidos en islas remotas, playas, comunidades costeras y zonas costeras evitando que contaminen nuestros océanos. Esta prenda contiene al menos un 40% de contenido reciclado en total.',
      images: [
        'pacer_adidas_x_marimekko_shorts_women_01.jpg',
        'pacer_adidas_x_marimekko_shorts_women_02.jpg',
        'pacer_adidas_x_marimekko_shorts_women_03.jpg',
      ],
      inStock: 25,
      price: 39.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'pacer_adidas_x_marimekko_shorts_women',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Pacer Adidas X Marimekko Shorts',
      gender: 'women',
    },
    {
      description:
        'Un traje de natacion llamativo diseñado en colaboracion con rich mnisi. Este producto esta hecho de tejido resistente al cloro que incorpora hilo ECONYL regenrado.',
      images: [
        'swimming_suit_rich_mnisi_women_01.jpg',
        'swimming_suit_rich_mnisi_women_02.jpg',
        'swimming_suit_rich_mnisi_women_03.jpg',
      ],
      inStock: 0,
      price: 59.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'rich_mnisi_swimming_suit_women',
      type: 'clothing',
      tags: ['swimming', 'suit'],
      title: 'Rich Mnisi Swimming Suit',
      gender: 'women',
    },
    {
      description:
        'Tenis de running receptivos con sujecion hechos parcialmente con materiales reciclados. Hechos con una serie de materiales reciclados, su exterior incorpora al menos un 50 % de contenido reciclado. Este producto representa solo una de nuestras soluciones para acabar con los residuos plasticos.',
      images: [
        'alphatorsion_2_0_men_01.jpg',
        'alphatorsion_2_0_men_02.jpg',
        'alphatorsion_2_0_men_03.jpg',
      ],
      inStock: 22,
      price: 124.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'alphatorsion_2_0',
      type: 'shoes',
      tags: ['running', 'sneakers'],
      title: 'Alphatorsion 2.0',
      gender: 'men',
    },
    {
      description:
        'Tenis inspirados en un famoso cervato y hechos parcialmente con parley ocean plastic. El exterior de este calzado esta confeccionado con hilo de alto rendimiento que contiene al menos un 50 % de Parley Ocean Plastic, un material que ha sido recuperado de residuos plásticos recogidos en islas, playas, comunidades costeras y costas evitando que contaminen nuestros oceanos. El otro 50 % del hilo esta hecho de poliester reciclado.',
      images: [
        'disney_nmd_r1_women_01.jpg',
        'disney_nmd_r1_women_02.jpg',
        'disney_nmd_r1_women_03.jpg',
      ],
      inStock: 33,
      price: 164.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
      ],
      slug: 'disney_nmd_r1_women_sneakers',
      type: 'shoes',
      tags: ['disney', 'sneakers'],
      title: 'Disney NMD_R1',
      gender: 'women',
    },
    {
      description:
        'Preparate para revolucionarlo todo. Los adidas Forum llevan implicita una actitud demoledora. Nacieron en 1984 para dominar las canchas de baloncesto; hoy son un icono en las calles. La correa ajustable y el diseño en forma de X conservan su esencia clasica. La paleta de colores se inspira en uno de los mejores equipos de la liga.',
      images: [
        'forum_84_men_01.jpg',
        'forum_84_men_02.jpg',
        'forum_84_men_03.jpg',
      ],
      inStock: 90,
      price: 149.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'forum_84',
      type: 'shoes',
      tags: ['basketball', 'sneakers'],
      title: 'Forum 84 high',
      gender: 'men',
    },
    {
      description:
        'Una nueva version de los tenis adidas superstar hechos parcialmente con materiales reciclados. A estas alturas, los tenis adidas Superstar no necesitan presentación. Conoces los hechos: nacidos en las canchas, adoptados por artistas del hip hop, usados en todas partes. Han pasado 50 años y la vibra es la misma. Lo que más te guste. Sé tú mismo. De eso se trata, y eso nunca cambiará. Lo que sí cambia en estos icónicos tenis son los colores y, para aportar un toque actual, agregamos un detalle de cuerda tejida en el costado. Las 3 Franjas con borde dentado y la punta de caucho con relieve: estas características legendarias siguen siendo tan relevantes como siempre.',
      images: [
        'superstar_women_01.jpg',
        'superstar_women_02.jpg',
        'superstar_women_03.jpg',
      ],
      inStock: 75,
      price: 104.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
      ],
      slug: 'superstar_women',
      type: 'shoes',
      tags: ['superstar', 'sneakers'],
      title: 'Superstar',
      gender: 'women',
    },
    {
      description:
        'Tenis de running creados por y para atletas. Cuando los adidas Ultraboost debutaron en el 2015 tuvieron un impacto que llegó mucho más allá que el mundo del running. Para esta versión de estos tenis, le incorporamos al diseño una suela de impresión 3D. Las partes más densas del entrelazado brindan un mayor soporte, y las parte más abiertas una mayor amortiguación. Estos tenis no solo se ven como el futuro. Se sienten como él.',
      images: [
        'ultra_4d_blanco_men_01.jpg',
        'ultra_4d_blanco_men_02.jpg',
        'ultra_4d_blanco_men_03.jpg',
      ],
      inStock: 150,
      price: 249.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'ultra_4d_blanco',
      type: 'shoes',
      tags: ['sneakers', 'running'],
      title: 'Ultra 4d',
      gender: 'men',
    },
    {
      description:
        'Tenis ultraboost hechos parcialmente con parley ocean plastic. Rich Mnisi es un diseñador sudafricano que se inspira en el mundo de la moda, desde el cine hasta la música y la naturaleza. En esta colaboración con adidas, imprime los icónicos estampados animales de su marca en los tenis de running Ultraboost. Desde el exterior de adidas PRIMEKNIT hasta la mediasuela BOOST, el diseño cobra vida con una historia de un lugar donde animales y la vida en la ciudad se encuentran.',
      images: [
        'ultraboost_22_rich_mnisi_women_01.jpg',
        'ultraboost_22_rich_mnisi_women_02.jpg',
        'ultraboost_22_rich_mnisi_women_03.jpg',
      ],
      inStock: 80,
      price: 199.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
      ],
      slug: 'ultraboost_22_rich_mnisi',
      type: 'shoes',
      tags: ['sneakers', 'running', 'ultraboost'],
      title: 'Ultraboost 22 Rich Mnisi',
      gender: 'women',
    },
    {
      description:
        'Ganadores del premio platino T3. El exterior de este calzado está confeccionado con hilo de alto rendimiento que contiene al menos un 50% de Parley Ocean Plastic, un material que ha sido recuperado de residuos plásticos recogidos en islas, playas, comunidades costeras y costas evitando que contaminen nuestros océanos. El otro 50% del hilo está hecho de poliéster reciclado.',
      images: [
        'ultraboost_22_women_01.jpg',
        'ultraboost_22_women_02.jpg',
        'ultraboost_22_women_03.jpg',
      ],
      inStock: 80,
      price: 199.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
      ],
      slug: 'ultraboost_22_women',
      type: 'shoes',
      tags: ['sneakers', 'running', 'ultraboost'],
      title: 'Ultraboost 22',
      gender: 'women',
    },
    {
      description:
        'Tenis progresivos con un estilo moderno. Si tuvieras que decidir entre estilo e innovación, ¿cuál escogerías? Pregunta tonta. No deberías tener que tomar una decisión así. Solo ponte estos tenis adidas ZX 5K Boost y sal a conquistar las calles. Inspirados en el espíritu innovador del código de diseño de los ZX, incorporan una mediasuela Boost envolvente en una suela traslúcida. Revestimientos de gamuza y detalles reflectivos adornan el exterior de malla para un estilo que brilla.',
      images: [
        'zx_5k_boost_blanco_men_01.jpg',
        'zx_5k_boost_blanco_men_02.jpg',
        'zx_5k_boost_blanco_men_03.jpg',
      ],
      inStock: 0,
      price: 189.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'zx_5k_boost_blanco_men',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'ZX 5K Boost',
      gender: 'men',
    },
    {
      description:
        'Una chamarra abrigada con una silueta estilizada. Luce bien. Siéntete bien. Ponte esta chamarra adidas para protegerte del frío cuando baja la temperatura. El aislamiento térmico sintético ofrece abrigo sin abultamientos para mayor libertad de movimiento y comodidad. Su corte entallado, cintura ajustable y materiales reciclados la hacen muy cómoda y perfecta para todo momento.',
      images: [
        'bsc_3_stripes_thermal_jacket_women_01.jpg',
        'bsc_3_stripes_thermal_jacket_women_02.jpg',
        'bsc_3_stripes_thermal_jacket_women_03.jpg',
      ],
      inStock: 19,
      price: 119.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'bsc_3_stripes_thermal_jacket',
      type: 'clothing',
      tags: ['jacket'],
      title: 'BSC 3 Stripes Thermal Jacket',
      gender: 'women',
    },
    {
      description:
        'Una playera ajustada de algodon con las iconicas 3 franjas. No te compliques: esta playera adidas hace más fácil tu vida. Mantén tu estilo auténtico y relajado con este look discreto pero no minimalista. El tejido de algodón suave te ofrece total comodidad en todo momento.',
      images: [
        'adicolor_classics_3_stripes_t_shirt_01.jpg',
        'adicolor_classics_3_stripes_t_shirt_02.jpg',
        'adicolor_classics_3_stripes_t_shirt_03.jpg',
      ],
      inStock: 55,
      price: 32.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'adicolor_classics_3_stripest_shirt',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Adicolor Classics 3 Stripes T-shirt',
      gender: 'men',
    },
    {
      description:
        'Padded Jacket es un nuevo producto para Hombre de adidas. Te invitamos a ver las imágenes para apreciar más detalles desde diferentes ángulos.',
      images: [
        'padded_jacket_men_01.jpg',
        'padded_jacket_men_02.jpg',
        'padded_jacket_men_03.jpg',
      ],
      inStock: 33,
      price: 214.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'padded_jacket_men',
      type: 'clothing',
      tags: ['jacket'],
      title: 'Padded jacket',
      gender: 'men',
    },
    {
      description:
        'Pants firebird que actualizan un estilo vintage. Un modelo clásico se actualiza. Estos pants adidas Firebird están inspirados en un diseño vintage japonés. También están hechos con materiales reciclados. ¿Quién iba a pensar que el plástico reciclado se podría transformar en tus nuevos pants favoritos?',
      images: [
        'adicolor_classics_firebird_primeblue_pants_01.jpg',
        'adicolor_classics_firebird_primeblue_pants_02.jpg',
        'adicolor_classics_firebird_primeblue_pants_03.jpg',
      ],
      inStock: 85,
      price: 74.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'adicolor_classics_firebird_primeblue_pants',
      type: 'clothing',
      tags: ['pants'],
      title: 'Adicolor Classics Firebird Primeblue Pants',
      gender: 'men',
    },
    {
      description:
        'Tenis para bebe para dias llenos de actividad. Estos tenis adidas fueron diseñados para que tu pequeño deportista disfrute de cada momento de juego y diversión. El tirador de talón y las tiras ajustables de cierre por contacto ofrecen un ajuste preciso y fácil de poner y de quitar. Su diseño inspirado en Mickey y Minnie Mouse les aporta un toque exclusivo.',
      images: [
        'tensaur_adidas_x_disney_mickey_and_minnie_01.jpg',
        'tensaur_adidas_x_disney_mickey_and_minnie_02.jpg',
        'tensaur_adidas_x_disney_mickey_and_minnie_03.jpg',
      ],
      inStock: 50,
      price: 52.45,
      sizes: [
        '1k',
        '2k',
        '3k',
        '4k',
        '5k',
        '5.5k',
        '6k',
        '6.5k',
        '7k',
        '7.5k',
        '8k',
        '8.5k',
        '9k',
        '9.5k',
        '10k',
      ],
      slug: 'tensaur_adidas_x_disney_mickey_and_minnie',
      type: 'shoes',
      tags: ['sneakers', 'disney'],
      title: 'Tensaur Adidas X Disney Mickey And Minnie',
      gender: 'boys',
    },
    {
      description:
        'Estos tenis para niños estan hechos parcialmente con materiales reciclados. Hecho con una serie de materiales reciclados, este exterior incorpora al menos un 50 % de contenido reciclado. Este producto representa solo una de nuestras soluciones para acabar con los residuos plásticos.',
      images: [
        'fortarun_running_shoes_01.jpg',
        'fortarun_running_shoes_02.jpg',
        'fortarun_running_shoes_03.jpg',
      ],
      inStock: 50,
      price: 69.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
        '3.5',
        '4',
        '4.5',
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
      ],
      slug: 'fortarun_running_shoes',
      type: 'shoes',
      tags: ['sneakers', 'running'],
      title: 'Fortarun',
      gender: 'boys',
    },
    {
      description:
        'Tenis muy comodos para pequeños exploradores. Para futuros basquetbolistas. Estos tenis para bebé le inyectan el ADN del básquet a un look sencillo para uso diario. Lucen un exterior de cuero sintético con detalles de malla y las 3 Franjas brillantes en los costados. Las tiras ajustables de cierre por contacto los hacen fáciles de poner y quitar.',
      images: [
        'hoops_20_sneakers_01.jpg',
        'hoops_20_sneakers_02.jpg',
        'hoops_20_sneakers_03.jpg',
      ],
      inStock: 50,
      price: 44.95,
      sizes: [
        '1k',
        '2k',
        '3k',
        '4k',
        '5k',
        '5.5k',
        '6k',
        '6.5k',
        '7k',
        '7.5k',
        '8k',
        '8.5k',
        '9k',
        '9.5k',
        '10k',
      ],
      slug: 'hoops_20_sneakers',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Hoops 2.0',
      gender: 'boys',
    },
    {
      description:
        'Una playera de algodon para los amigos de Mickey Mouse. Inspirada en el adorable ratón de dibujos animados, esta playera adidas para niños celebra la alegría de la amistad. El tejido de algodón suave y el corte holgado la hacen muy cómoda para que puedas jugar a diario.',
      images: [
        'adidas_x_disney_mickey_mouse_t_shirt_01.jpg',
        'adidas_x_disney_mickey_mouse_t_shirt_02.jpg',
        'adidas_x_disney_mickey_mouse_t_shirt_03.jpg',
      ],
      inStock: 0,
      price: 32.45,
      sizes: [
        '2 years',
        '3 years',
        '4 years',
        '5 years',
        '5-6 years',
        '7-8 years',
        '9-10 years',
      ],
      slug: 'adidas_x_disney_mickey_mouse_t_shirt',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Adidas X Disney Mickey Mouse T-shirt',
      gender: 'boys',
    },
    {
      description:
        'Una chamarra adidas x Disney hecha parcialmente con materiales reciclados. ¿Necesitas un recordatorio para relajarte? Esta chamarra adidas para jóvenes te envuelve en comodidad con sus estampados de Disney. El material de tejido de tricot suave y clásico también ayuda.',
      images: [
        'sst_disney_mickey_and_friends_jacket_01.jpg',
        'sst_disney_mickey_and_friends_jacket_02.jpg',
        'sst_disney_mickey_and_friends_jacket_03.jpg',
      ],
      inStock: 66,
      price: 32.45,
      sizes: [
        '7-8 years',
        '9-10 years',
        '11-12 years',
        '13-14 years',
        '15-16 years',
      ],
      slug: 'sst_disney_mickey_and_friends_jacket',
      type: 'clothing',
      tags: ['jacket'],
      title: 'SST Disney Mickey And Friends Jacket ',
      gender: 'boys',
    },
    {
      description:
        'Shorts livianos con un llamativo estampado LEGO. No tienes porque lucir siempre igual en tus entrenamientos. Cambia tu estilo con estos shorts adidas para jóvenes. La cintura elástica con cordón de ajuste brinda cobertura mientras haces movimientos exigentes. El bolsillo trasero oculto con cierre de cremallera mantiene tus objetos esenciales a la mano.',
      images: [
        'adidas_x_classic_lego_shorts_01.jpg',
        'adidas_x_classic_lego_shorts_02.jpg',
        'adidas_x_classic_lego_shorts_03.jpg',
      ],
      inStock: 99,
      price: 49.95,
      sizes: [
        '7-8 years',
        '9-10 years',
        '11-12 years',
        '13-14 years',
        '15-16 years',
      ],
      slug: 'adidas_x_classic_lego_shorts',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Adidas X Classic LEGO Shorts',
      gender: 'boys',
    },
    {
      description:
        'Tenis para bebe que celebran la realeza. A tu bebé a veces le cuesta elegir cuál es su princesa favorita. Por suerte, con estos tenis adidas no tendrá que hacerlo. Presentan un exterior de piel sintética muy resistente al desgaste y un cierre con tiras ajustables de cierre por contacto que le ofrece un ajuste seguro.',
      images: [
        'breaknet_adidas_x_disney_princess_sneakers_01.jpg',
        'breaknet_adidas_x_disney_princess_sneakers_02.jpg',
        'breaknet_adidas_x_disney_princess_sneakers_03.jpg',
      ],
      inStock: 53,
      price: 49.95,
      sizes: [
        '1k',
        '2k',
        '3k',
        '4k',
        '5k',
        '5.5k',
        '6k',
        '6.5k',
        '7k',
        '7.5k',
        '8k',
        '8.5k',
        '9k',
        '9.5k',
        '10k',
      ],
      slug: 'breaknet_adidas_x_disney_princess_sneakers_',
      type: 'shoes',
      tags: ['sneakers', 'disney'],
      title: 'Breaknet Adidas X Disney Princess',
      gender: 'girls',
    },
    {
      description:
        'Tenis cde running comodos para bebe. La mediasuela LIGHTMOTION de estos tenis de running adidas para bebé le inyectan comodidad y amortiguación a cada paso de tu peque. Los cordones elásticos y la tira ajustable de cierre por contacto los mantienen en su lugar mientras se mueven con fluidez por cada rincón de la casa.',
      images: [
        'duramo_10_sneakers_girls_01.jpg',
        'duramo_10_sneakers_girls_02.jpg',
        'duramo_10_sneakers_girls_03.jpg',
      ],
      inStock: 150,
      price: 59.95,
      sizes: [
        '1k',
        '2k',
        '3k',
        '4k',
        '5k',
        '5.5k',
        '6k',
        '6.5k',
        '7k',
        '7.5k',
        '8k',
        '8.5k',
        '9k',
        '9.5k',
        '10k',
      ],
      slug: 'duramo_10_sneakers_girls',
      type: 'shoes',
      tags: ['sneakers', 'running'],
      title: 'Duramo 10',
      gender: 'girls',
    },
    {
      description:
        'Tenis stan smith para los mas pequeños hechos con marimekko. Brillante, audaz y lleno de alegría. ¿Te suena a tu peque? También es el espíritu detrás de la casa de diseño finlandesa Marimekko. Han estado iluminando el mundo con colores y estampados vibrantes desde los años 50. Ahora, su icónico diseño Unikko está sobre estos tenis adidas Stan Smith para bebé en dorado metalizado. Envuelve sus pies con estos cómodos tenis y deja que se enfrenten a los retos del día con estilo.',
      images: [
        'stan_smith_marimekko_sneakers_01.jpg',
        'stan_smith_marimekko_sneakers_02.jpg',
        'stan_smith_marimekko_sneakers_03.jpg',
      ],
      inStock: 150,
      price: 59.95,
      sizes: [
        '1k',
        '2k',
        '3k',
        '4k',
        '5k',
        '5.5k',
        '6k',
        '6.5k',
        '7k',
        '7.5k',
        '8k',
        '8.5k',
        '9k',
        '9.5k',
        '10k',
      ],
      slug: 'stan_smith_marimekko_sneakers',
      type: 'shoes',
      tags: ['sneakers', 'marimekko', 'stan', 'smith'],
      title: 'Stan Smith Marimekko',
      gender: 'girls',
    },
    {
      description:
        'Una playera absorbente hecha con materiales reciclados. Incorpora tecnología de absorción AEROREADY que se encarga de mantener su piel seca en todo momento. El corte holgado y alargado les permiten lucir un estilo diferente cada vez que la usan. La tinta brillante y el lindo estampado de Daisy Duck de Disney le dan un toque glamuroso',
      images: [
        'disney_daisy_duck_t_shirt_01.jpg',
        'disney_daisy_duck_t_shirt_02.jpg',
        'disney_daisy_duck_t_shirt_03.jpg',
      ],
      inStock: 66,
      price: 32.45,
      sizes: [
        '2 years',
        '3 years',
        '4 years',
        '5 years',
        '5-6 years',
        '7-8 years',
        '9-10 years',
      ],
      slug: 'disney_daisy_duck_t_shirt',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Disney Daisy Duck T-shirt',
      gender: 'girls',
    },
    {
      description:
        "An adidas sweatshirt with famous pals. Nothing's better than a high-five among friends. Gear up your star player for fun in this kids' adidas sweatshirt. Lifelong besties Disney's Minnie Mouse and Daisy Duck bring the teamwork, so your active youngster can make the dream work. They'll feel warm and comfy for all-day play, thanks to soft fleece.",
      images: [
        'adidas_x_disney_daisy_duck_crew_sweatshirt_01.jpg',
        'adidas_x_disney_daisy_duck_crew_sweatshirt_02.jpg',
        'adidas_x_disney_daisy_duck_crew_sweatshirt_03.jpg',
      ],
      inStock: 77,
      price: 24.95,
      sizes: ['2 years', '3 years', '4 years', '5 years'],
      slug: 'adidas_x_disney_daisy_duck_crew_sweatshirt',
      type: 'clothing',
      tags: ['sweatshirt'],
      title: 'Adidas X Disney Daisy Duck Crew Sweatshirt',
      gender: 'girls',
    },
    {
      description:
        "This flower-print track jacket is made with recycled materials. Flowers make us feel empowered. You can really tell with this juniors' adidas track jacket. The iconic SST track suit silhouette features an allover print that draws meaning from the flowers in its design. We're highlighting gerbera daisy for strength, iris for hope and freesia for positive energy.",
      images: [
        'allover_flower_print_sst_track_jacket_01.jpg',
        'allover_flower_print_sst_track_jacket_02.jpg',
        'allover_flower_print_sst_track_jacket_03.jpg',
      ],
      inStock: 102,
      price: 59.95,
      sizes: [
        '7-8 years',
        '9-10 years',
        '11-12 years',
        '13-14 years',
        '15-16 years',
      ],
      slug: 'allover_flower_print_sst_track_jacket',
      type: 'clothing',
      tags: ['jacket'],
      title: 'Allover Flower Print SST Track Jacket',
      gender: 'girls',
    },
    {
      description:
        'Aprovecha la energía. El sistema de amortiguación rediseñado combina Max Air visibles con una unidad Zoom Air gruesa y con respuesta inmediata. El Max Air disipa las fuerzas de impacto, mientras que el Zoom Air mejora tu paso en la cancha.',
      images: [
        'lebron_19_men_01.jpg',
        'lebron_19_men_02.jpg',
        'lebron_19_men_03.jpg',
      ],
      inStock: 114,
      price: 214.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'lebron_19',
      type: 'shoes',
      tags: ['sneakers', 'basketball'],
      title: 'LeBron 19',
      gender: 'men',
    },
    {
      description:
        'Nada tan genial, nada tan cómodo, nada tan eficaz: el Air Max 90 te brinda un estilo primaveral al caminar. Con detalles divertidos, desde la seta en el talón hasta la mariposa en la plantilla, ofrece una sensación de verano. Además, te permite hacer el bien y verte bien.',
      images: [
        'nike_air_max_90_01.jpg',
        'nike_air_max_90_02.jpg',
        'nike_air_max_90_03.jpg',
      ],
      inStock: 114,
      price: 139.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'nike_air_max_90',
      type: 'shoes',
      tags: ['sneakers', 'max'],
      title: 'Nike Air Max 90',
      gender: 'men',
    },
    {
      description:
        'Nike Waffle One equilibra todo lo que más te gusta de la herencia Nike Running con nuevas innovaciones.Su nuevo y duradero pasador de talón de plástico agrega energía mientras que una mezcla de malla transparente y exquisita gamuza te prepara para el verano.La nueva entresuela elástica cuenta con la clásica forma de cuña que ya conoces, mientras que la suela tipo wafle actualizada brinda un nivel de soporte y tracción que debes sentir para creer.',
      images: [
        'nike_waffle_one_men_01.jpg',
        'nike_waffle_one_men_02.jpg',
        'nike_waffle_one_men_03.jpg',
      ],
      inStock: 200,
      price: 114.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'nike_waffle_one_men',
      type: 'shoes',
      tags: ['sneakers', 'running', 'waffle'],
      title: 'Nike Waffle One',
      gender: 'men',
    },
    {
      description:
        'Inicia tu ruta diaria con la camiseta Nike Dri-FIT Miler.Ofrece rendimiento ligero y movilidad para el corredor de nivel inicial.Este producto está fabricado con al menos un 50% de fibras de poliéster reciclado.',
      images: [
        'nike_dri_fit_miler_01.jpg',
        'nike_dri_fit_miler_02.jpg',
        'nike_dri_fit_miler_03.jpg',
      ],
      inStock: 77,
      price: 37.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_dri_fit_miler',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Nike Dri-FIT Miler T-Shirt',
      gender: 'men',
    },
    {
      description:
        'Los shorts AeroSwift Nike te mantienen listo para tu carrera con un diseño ligero.La tecnología absorbente de sudor y la pretina ventilada te ayudan a mantenerte seco y fresco mientras corres.Este producto está fabricado con al menos un 75% de fibras de poliéster reciclado.',
      images: [
        'nike_aeroswift_men_01.jpg',
        'nike_aeroswift_men_02.jpg',
        'nike_aeroswift_men_03.jpg',
      ],
      inStock: 113,
      price: 84.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_aeroswift',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Nike AeroSwift Shorts',
      gender: 'men',
    },
    {
      description:
        'Pasa directamente de la cancha a la calle con la sudadera sin cierre Nike Standard Issue. Está elaborada con un tejido Fleece suave y estructurado con un ajuste holgado. La tecnología Dri-FIT absorbente de sudor y los laterales flexibles hacen que sea una opción ideal para la cancha.',
      images: [
        'nike_standard_issue_sweatshirt_01.jpg',
        'nike_standard_issue_sweatshirt_02.jpg',
        'nike_standard_issue_sweatshirt_03.jpg',
      ],
      inStock: 107,
      price: 62.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_standard_issue_sweatshirt',
      type: 'clothing',
      tags: ['sweatshirt'],
      title: 'Nike AeroSwift Sweatshirt',
      gender: 'men',
    },
    {
      description:
        'Dales un poco de sol a tus pies. Los detalles desenfadados y los colores frescos aportan vibras de playa al estilo clásico del Dunk. Las telas aireadas canalizan el estilo veraniego, mientras que el cuello acolchado de corte bajo te permite llevar tu juego a cualquier lugar, con comodidad.',
      images: [
        'nike_dunk_low_se_women_01.jpg',
        'nike_dunk_low_se_women_02.jpg',
        'nike_dunk_low_se_women_03.jpg',
      ],
      inStock: 200,
      price: 134.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'nike_dunk_low_se_women',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nike Dunk Low SE',
      gender: 'women',
    },
    {
      description:
        'Permite que una nueva onda de estilo se apodere de ti con el Nike Fontanka Waffle. El diseño atlético elegante, que combina la moda con el deporte, rinde homenaje al Daybreak icónico y presenta detalles de gamuza clásicos y una suela tipo waffle. Los Swoosh bordados, las costuras decorativas y el cuello suave fusionan la artesanía con la comodidad.',
      images: [
        'nike_fontanka_waffle_women_01.jpg',
        'nike_fontanka_waffle_women_02.jpg',
        'nike_fontanka_waffle_women_03.jpg',
      ],
      inStock: 117,
      price: 109.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
      ],
      slug: 'nike_fontanka_waffle_women',
      type: 'shoes',
      tags: ['sneakers', 'waffle'],
      title: 'Nike Fontanka Waffle',
      gender: 'women',
    },
    {
      description:
        'Podríamos usar muchos superlativos para describir este calzado. Podríamos decirte que el nuevo sistema de amortiguación Air ofrece la sensación más revolucionaria que hayas experimentado. O que la parte central de la suela de espuma te brinda la sensación más ligera y suave. Pero ¿qué gracia tiene adelantar las sorpresas? Amarra tus agujetas y disfruta la nueva era del diseño Air.',
      images: [
        'nike_air_max_2021_women_01.jpg',
        'nike_air_max_2021_women_02.jpg',
        'nike_air_max_2021_women_03.jpg',
      ],
      inStock: 186,
      price: 179.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
      ],
      slug: 'nike_air_max_2021_women',
      type: 'shoes',
      tags: ['sneakers', 'max'],
      title: 'Nike Air Max 2021',
      gender: 'women',
    },
    {
      description:
        'La playera Nike Swoosh Run está diseñada para todas tus carreras: cortas y largas. La tela suave y tersa tiene un estilo transpirable para mantener una frescura libre de humedad. Este producto está fabricado al 100% con fibras de poliéster reciclado.',
      images: [
        'nike_swoosh_run_t_shirt_01.jpg',
        'nike_swoosh_run_t_shirt_02.jpg',
        'nike_swoosh_run_t_shirt_03.jpg',
      ],
      inStock: 99,
      price: 39.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_swoosh_run_t_shirt',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Nike Swoosh Run T-shirt',
      gender: 'women',
    },
    {
      description:
        'Por encima de todo, necesitas flexibilidad en tu rutina y en lo que usas para entrenar. Estos leggings ligeros son una segunda piel que no querrás quitarte nunca. Confeccionados con tela suave y sedosa que no se transluce, te mantienen segura y cubierta para cualquier entrenamiento, e incluso para el resto del día. Este producto está fabricado con al menos un 50% de fibras de poliéster reciclado.',
      images: [
        'nike_dri_fit_one_luxe_icon_clash_tights_women_01.jpg',
        'nike_dri_fit_one_luxe_icon_clash_tights_women_02.jpg',
        'nike_dri_fit_one_luxe_icon_clash_tights_women_03.jpg',
      ],
      inStock: 113,
      price: 92.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_dri_fit_one_luxe_icon_clash_tights',
      type: 'clothing',
      tags: ['tights'],
      title: 'Nike Dri-FIT One Luxe Icon Clash Tights',
      gender: 'women',
    },
    {
      description:
        'Esta chamarra es bastante ligera para mantener notablemente la velocidad, está lista para convertirse en tu nueva prenda favorita; está diseñada para mantener la transpirabilidad y protección en climas húmedos. ¿Necesitas quitarte capas a la mitad de tu carrera? No hay problema, la chamarra se puede guardar dentro de sí misma para transportarla con facilidad. Este producto está fabricado con al menos un 75% de fibras de poliéster reciclado.',
      images: [
        'nike_running_jacket_women_01.jpg',
        'nike_running_jacket_women_02.jpg',
        'nike_running_jacket_women_03.jpg',
      ],
      inStock: 300,
      price: 104.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_running_jacket',
      type: 'clothing',
      tags: ['jacket'],
      title: 'Nike Running Jacket',
      gender: 'women',
    },
    {
      description:
        'Fácil, cómodo y hecho para jugar en cualquier momento, el calzado Nike Dynamo Go será el próximo favorito de tu pequeño. Lo que más nos gusta es que los niños pueden pisar el talón plegable y ponérselo rápidamente. Y si no están preparados para hacerlo ellos mismos, puedes mostrarles cómo funciona para que puedan ser libres e independientes. También es suave y acolchado en los lugares precisos para que la diversión nunca se detenga.',
      images: [
        'nike_dynamo_go_01.jpg',
        'nike_dynamo_go_02.jpg',
        'nike_dynamo_go_03.jpg',
      ],
      inStock: 113,
      price: 84.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'nike_dynamo_go',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nike Dynamo Go',
      gender: 'girls',
    },
    {
      description:
        'El Nike Court Borough Low 2 aporta esa potencia rosa para las futuras estrellas. Desde las agujetas hasta el diseño Swoosh y la suela, el rosa no solo es un color, es una actitud. Este calzado también es duradero y ofrece el look y la sensación clásicos de la cancha, listo para el juego de todos los días.',
      images: [
        'nike_court_borough_low_2_01.jpg',
        'nike_court_borough_low_2_02.jpg',
        'nike_court_borough_low_2_03.jpg',
      ],
      inStock: 140,
      price: 59.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'nike_court_borough_low_2',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nike Court Borough Low 2',
      gender: 'girls',
    },
    {
      description:
        'Este calzado para todos los días vuelve al pasado con una combinación de detalles del calzado de running de los años 80. Además, el Nike MD Valiant está lleno de historia. Se le llama así por el carro en el que el cofundador de Nike vendía el calzado cuando empezó todo: un Valiant del 64.',
      images: [
        'nike_md_valiant_01.jpg',
        'nike_md_valiant_02.jpg',
        'nike_md_valiant_03.jpg',
      ],
      inStock: 140,
      price: 62.45,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'nike_md_valiant',
      type: 'shoes',
      tags: ['sneakers', 'running'],
      title: 'Nike MD Valiant',
      gender: 'girls',
    },
    {
      description:
        'Mira todos los gráficos jugosos de la camiseta de tirantes de Nike Sportswear. Están inspirados en nuestras pegatinas favoritas de frutas que se ven en la tienda de alimentos. ¿Cuál es tu favorito?',
      images: [
        'nike_sportswear_tank_top_01.jpg',
        'nike_sportswear_tank_top_02.jpg',
        'nike_sportswear_tank_top_03.jpg',
      ],
      inStock: 111,
      price: 29.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_sportswear_tank_top',
      type: 'clothing',
      tags: ['tank', 'top', 't_shirt'],
      title: 'Nike Sportswear Tank Top',
      gender: 'girls',
    },
    {
      description:
        'Los Nike Dri-FIT One Luxe son nuestros leggigns más versátiles— confeccionados con tela suave y sedosa para jugar o para lo que sea. Como parte de la línea Nike One Luxe, son supercómodos y ligeros, como un abrazo que dura todo el día. El agregado de un estampado floral colorido hace que se vean aún mejor.',
      images: [
        'nike_dri_fit_one_luxe_tights_01.jpg',
        'nike_dri_fit_one_luxe_tights_02.jpg',
        'nike_dri_fit_one_luxe_tights_03.jpg',
      ],
      inStock: 200,
      price: 39.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_dri_fit_one_luxe_tights',
      type: 'clothing',
      tags: ['tights'],
      title: 'Nike Dri-FIT One Luxe Tights',
      gender: 'girls',
    },
    {
      description:
        'Estamos de acuerdo en que todos los días son mejores con una sudadera. Para ir a tu parque favorito o salir a la calle con tus amigos, siempre es tu prenda imprescindible. La sudadera con gorro Nike Sportswear está confeccionada con toda la sensación acogedora del tejido Fleece, además de un diseño Swoosh que te encantará al instante.',
      images: [
        'nike_sportswear_sweatshirt_01.jpg',
        'nike_sportswear_sweatshirt_02.jpg',
        'nike_sportswear_sweatshirt_03.jpg',
      ],
      inStock: 200,
      price: 44.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_sportswear_sweatshirt',
      type: 'clothing',
      tags: ['sweatshirt'],
      title: 'Nike Sportswear Sweatshirt',
      gender: 'girls',
    },
    {
      description:
        'El Nike Force 1 Crater tiene un secreto divertido: está hecho con al menos un 20% de contenido reciclado. El diseño transparente permite ver a través de este calzado legendario. Además, la suave espuma Crater utiliza goma Nike Grind para brindar una sensación única y ligera.',
      images: [
        'nike_air_force_1_crater_01.jpg',
        'nike_air_force_1_crater_02.jpg',
        'nike_air_force_1_crater_03.jpg',
      ],
      inStock: 133,
      price: 99.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'nike_air_force_1_crater',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nike Air Force 1 Crater',
      gender: 'boys',
    },
    {
      description:
        'Desde el perímetro hasta el aro, domina la cancha con confianza. Este es uno de los calzados de juego Air Jordan más ligeros hasta la fecha, con una parte superior minimalista pero duradera de tejido Leno reforzado con detalles de plástico resistentes. Además, la amortiguación Zoom Air brinda retorno de energía y capacidad de respuesta de élite. El juego te pide todo. Ahora tienes el calzado para combinar.',
      images: [
        'air_jordan_xxxvl_luka_01.jpg',
        'air_jordan_xxxvl_luka_02.jpg',
        'air_jordan_xxxvl_luka_03.jpg',
      ],
      inStock: 266,
      price: 159.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'air_jordan_xxxvl_luka',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Air Jordan XXXVI Luka',
      gender: 'boys',
    },
    {
      description:
        'Pon el sol a tus pies con el Nike Air Max 90 SE Next Nature. Los detalles relajados y los colores frescos brindan un estilo de día de playa, mientras que las telas ventiladas de verano mantienen tus pies frescos. ¿Lo mejor de todo? Incluye una unidad (Max) Air para brindar comodidad durante todo el día.',
      images: [
        'nike_air_max_90_se_next_nature_01.jpg',
        'nike_air_max_90_se_next_nature_02.jpg',
        'nike_air_max_90_se_next_nature_03.jpg',
      ],
      inStock: 132,
      price: 119.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'nike_air_max_90_se_next_nature',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nike Air Max 90 SE Next Nature',
      gender: 'boys',
    },
    {
      description:
        'Hazla en grande y con valentía o vete a casa. Los shorts Nike Sportswear son una prenda básica y ligera para el clima cálido con un estampado increíble dibujado a mano inspirado en el logotipo y un cordón de ajuste externo único.',
      images: [
        'nike_sportswear_french_terry_shorts_01.jpg',
        'nike_sportswear_french_terry_shorts_02.jpg',
        'nike_sportswear_french_terry_shorts_03.jpg',
      ],
      inStock: 89,
      price: 37.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_sportswear_french_terry_shorts',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Nike Sportswear French Terry Shorts',
      gender: 'boys',
    },
    {
      description:
        'La camiseta Nike Dri-FIT Academy es una prenda básica de fútbol diseñada para el entrenamiento diario.Combina una tela suave absorbente de sudor con paneles de malla para mantener la frescura en el calor del juego.Este producto está fabricado al 100% con fibras de poliéster reciclado.',
      images: [
        'nike_dri_fit_academy_t_shirt_01.jpg',
        'nike_dri_fit_academy_t_shirt_02.jpg',
        'nike_dri_fit_academy_t_shirt_03.jpg',
      ],
      inStock: 189,
      price: 19.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_dri_fit_academy_t_shirt',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Nike Dri-FIT Academy T-Shirt',
      gender: 'boys',
    },
    {
      description:
        'La sudadera con gorro Nike Sportswear Club es idea para los días fríos. Consejo: esta prenda se puede combinar con pants de tiro alto para lucir un look con el que te sentirás bien en cualquier situación.',
      images: [
        'nike_sportswear_club_sweatshirt_01.jpg',
        'nike_sportswear_club_sweatshirt_02.jpg',
        'nike_sportswear_club_sweatshirt_03.jpg',
      ],
      inStock: 117,
      price: 42.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'nike_sportswear_club_sweatshirt',
      type: 'clothing',
      tags: ['sweatshirt'],
      title: 'Nike Sportswear Club Sweatshirt',
      gender: 'boys',
    },
    {
      description:
        'Tenis originales que fusionaron lo retro con lo moderno. Modernos, veloces y futurísticos. Eso es lo que obtienes con los Reebok Classic Leather Legacy AZ para mujer. Increíbles desde todos los ángulos gracias a las líneas de diseño geométrico. La evolución del icónico estabilizador de talón de TPU les da un look audaz. Los detalles de color contrastante añaden un toque llamativo. La capellada mezcla capas suaves y texturizadas con una estructura de tela y gamuza. No te pierdas los bordes serrados de la lengüeta que crean un look retro.',
      images: [
        'classic_legacy_az_women_01.jpg',
        'classic_legacy_az_women_02.jpg',
        'classic_legacy_az_women_03.jpg',
      ],
      inStock: 207,
      price: 99.95,
      sizes: ['5', '5.5', '6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10'],
      slug: 'classic_legacy_az_women',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Classic Legacy AZ',
      gender: 'women',
    },
    {
      description:
        'Unos tenis de entrenamiento versatiles diseñados para darte soporte. Desde pistol squats hasta burpees, domina todos los movimientos que llevarán tu entrenamiento al próximo nivel. Usa estos tenis Reebok para mujer y mantente cómoda y segura en todo momento. Su capellada de tejido Flexweave® es transpirable y resistente, y cuenta con soporte integrado para movimientos estables en todas las direcciones. La suela de caucho con patrón de tacos en zonas estratégicas te brinda tracción segura.',
      images: [
        'nano_x2_reebok_women_01.jpg',
        'nano_x2_reebok_women_02.jpg',
        'nano_x2_reebok_women_03.jpg',
      ],
      inStock: 221,
      price: 144.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
      ],
      slug: 'nano_x2_reebok_women',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Nano X2 Reebok',
      gender: 'women',
    },
    {
      description:
        'Unos tenis de entrenamiento versatiles diseñados para darte soporte. Desde pistol squats hasta burpees, domina todos los movimientos que llevarán tu entrenamiento al próximo nivel. Usa estos tenis Reebok para mujer y mantente cómoda y segura en todo momento. Su capellada de tejido Flexweave® es transpirable y resistente, y cuenta con soporte integrado para movimientos estables en todas las direcciones. La suela de caucho con patrón de tacos en zonas estratégicas te brinda tracción segura.',
      images: [
        'princess_women_01.jpg',
        'princess_women_02.jpg',
        'princess_women_03.jpg',
      ],
      inStock: 221,
      price: 69.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
      ],
      slug: 'princess_women',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Princess',
      gender: 'women',
    },
    {
      description:
        'Playera de cuello redondo. En el gym o en la pista, da siempre lo mejor de ti. Esta playera para mujer está confeccionada en tejido elástico que te permite hacer todo tipo de movimientos sin restricción. Su corte entallado te aporta un look estilizado.',
      images: [
        'workout_ready_speedwick_tee_01.jpg',
        'workout_ready_speedwick_tee_02.jpg',
        'workout_ready_speedwick_tee_03.jpg',
      ],
      inStock: 173,
      price: 27.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'workout_ready_speedwick_tee',
      type: 'clothing',
      tags: ['t_shirt'],
      title: 'Workout Ready Speedwick Tee',
      gender: 'women',
    },
    {
      description:
        'Mallas hechas con un minimo de 30% de materiales reciclados. ¡Olvídate de sutilezas! Sal a brillar con estas mallas Reebok para mujer. El estampado integral no pasará desapercibido y te llenará de energía para que puedas dar lo mejor de ti en tu entrenamiento. La pretina ancha y elástica viene con un panel antirozaduras para tu comodidad. Una prenda hecha con materiales reciclados para que puedas sentirte bien con lo que llevas puesto.',
      images: [
        'lux_bold_tights_01.jpg',
        'lux_bold_tights_02.jpg',
        'lux_bold_tights_03.jpg',
      ],
      inStock: 111,
      price: 64.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'lux_bold_tights',
      type: 'clothing',
      tags: ['tights'],
      title: 'Lux Bold Tights',
      gender: 'women',
    },
    {
      description:
        'Shorts de running hechos con materiales reciclados. Haz que tu sesión de running sea la mejor parte de tu día. Estos shorts de running Reebok para mujer te ayudarán a lograrlo. La tecnología Speedwick mantiene tu cuerpo seco mientras tú encuentras tu ritmo ideal. Vienen con un forro interior que aumenta la circulación del aire y te mantiene seca.',
      images: [
        'running_shorts_women_01.jpg',
        'running_shorts_women_02.jpg',
        'running_shorts_women_03.jpg',
      ],
      inStock: 99,
      price: 42.45,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'running_shorts_women',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Running Shorts',
      gender: 'women',
    },
    {
      description:
        'Tenis ligeros para entrenar y levantar peso. Pasa de entrenamientos con pesas a cardio sin perderte ni un respiro, ni parar a cambiarte los tenis. Estos tenis Reebok para entrenar están diseñados para ofrecerte versatilidad en el gym. Vienen con una capellada de malla transpirable sobre una mediasuela de espuma Floatride Energy para máximo confort. Una cuña en la zona media ofrece estabilidad para realizar levantamientos de pesas, y el chasis de velocidad brinda soporte en la zona media del pie.',
      images: [
        'speed_21_tr_men_01.jpg',
        'speed_21_tr_men_02.jpg',
        'speed_21_tr_men_03.jpg',
      ],
      inStock: 243,
      price: 139.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
        '12.5',
        '13',
        '13.5',
        '14',
      ],
      slug: 'speed_21_tr_men',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Speed 21 TR',
      gender: 'men',
    },
    {
      description:
        'Tenis veganos con una estetica minimalista. Combina tus principios con tu estilo. Estos tenis Reebok para hombre vienen con una suela de caucho natural y una capellada de piel sintética, además de una plantilla y refuerzo de talón con el logo vegano de Reebok. La cincha bicolor se mantiene fiel a la estética original y añade un toque de color.',
      images: [
        'npc_uk_ll_vegan_men_01.jpg',
        'npc_uk_ll_vegan_men_02.jpg',
        'npc_uk_ll_vegan_men_03.jpg',
      ],
      inStock: 243,
      price: 139.95,
      sizes: [
        '5',
        '5.5',
        '6',
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
        '12.5',
        '13',
      ],
      slug: 'npc_uk_ll_vegan_men',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'NPC UK II Vegan',
      gender: 'men',
    },
    {
      description: 'Tenis de running con amortiguacion reactiva.',
      images: [
        'liquifect_90_men_01.jpg',
        'liquifect_90_men_02.jpg',
        'liquifect_90_men_03.jpg',
      ],
      inStock: 111,
      price: 89.95,
      sizes: [
        '6.5',
        '7',
        '7.5',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '12',
        '12.5',
        '13',
        '13.5',
        '14',
      ],
      slug: 'liquifect_90_men',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Liquifect 90',
      gender: 'men',
    },
    {
      description:
        'Un playera sin mangas ligera y ventilada. Prepárate para salir a correr o en bici. Esta playera Reebok para hombre está diseñada para ofrecerte confort y ligereza. Presenta un corte ajustado que no se interpone con tus movimientos. La tecnología Speedwick repele el sudor para mantenerte seco, y las perforaciones en el panel posterior aportan ventilación.',
      images: [
        'united_by_fitness_speed_tank_top_01.jpg',
        'united_by_fitness_speed_tank_top_02.jpg',
        'united_by_fitness_speed_tank_top_03.jpg',
      ],
      inStock: 77,
      price: 42.45,
      sizes: ['S', 'M', 'L', 'XL'],
      slug: 'united_by_fitness_speed_tank_top',
      type: 'clothing',
      tags: ['tank_top'],
      title: 'United By Fitness Speed Tank Top',
      gender: 'men',
    },
    {
      description:
        'Ts Epic Lightweight Short es un nuevo producto para Hombre de Reebok. Te invitamos a ver las imágenes para apreciar más detalles desde diferentes ángulos.',
      images: [
        'graphic_epic_lightweight_men_01.jpg',
        'graphic_epic_lightweight_men_02.jpg',
        'graphic_epic_lightweight_men_03.jpg',
      ],
      inStock: 111,
      price: 54.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'graphic_epic_lightweight_men',
      type: 'clothing',
      tags: ['shorts'],
      title: 'Graphic Epic Lightweight Shorts',
      gender: 'men',
    },
    {
      description:
        'Una sudadera de felpa que puedes usar para ir a cualquier lugar. Sube las escaleras del parque y levanta los brazos como un auténtico campeón. O simplemente, quédate en casa y disfruta de tu programa de deportes favorito. Sea lo que sea lo que te depare el día, esta sudadera de entrenamiento para hombre va contigo. Su tejido de felpa de mezcla de algodón se siente suave sobre tu piel. El logo Reebok en el pecho le infunde un look deportivo.',
      images: [
        'reebok_identity_zip_up_sweatshirt_01.jpg',
        'reebok_identity_zip_up_sweatshirt_02.jpg',
        'reebok_identity_zip_up_sweatshirt_03.jpg',
      ],
      inStock: 59,
      price: 59.95,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      slug: 'reebok_identity_zip_up_sweatshirt',
      type: 'clothing',
      tags: ['sweatshirt'],
      title: 'Reebok Identity Zp-Up Sweatshirt',
      gender: 'men',
    },
    {
      description:
        'Corre. Salta. Colúmpiate. Repite. Estos tenis de running Reebok para niñas están diseñados para seguirle el ritmo a su estilo de vida activo. Vienen con una capellada de tela ligera para que nada la detenga. Jugará todo el día con comodidad gracias a la amortiguación de la mediasuela y suela de EVA.',
      images: [
        'rush_runner_4_reebok_girls_01.jpg',
        'rush_runner_4_reebok_girls_02.jpg',
        'rush_runner_4_reebok_girls_03.jpg',
      ],
      inStock: 400,
      price: 52.45,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
        '3.5',
        '4',
      ],
      slug: 'rush_runner_4_reebok_girls',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Rush Runner 4 Reebok',
      gender: 'girls',
    },
    {
      description:
        'A veces la imaginación lleva a tu peque a vivir aventuras en la selva. Estos tenis Reebok para niñas le dan toda la energía que necesita para divertirse gracias al estampado de guepardo. El cierre de tira por contacto hace que sean fáciles de poner y quitar. Porque hasta los grandes gatitos tienen que volver a casa a la hora de la cena.',
      images: [
        'reebok_royal_complete_cln_2_girls_01.jpg',
        'reebok_royal_complete_cln_2_girls_02.jpg',
        'reebok_royal_complete_cln_2_girls_03.jpg',
      ],
      inStock: 67,
      price: 49.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'reebok_royal_complete_cln_2_girls',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Reebok Royal Complete CLN 2',
      gender: 'girls',
    },
    {
      description:
        'Estilo icónico para los pies de tu pequeña. Estos tenis para niñas vienen cargados de herencia Reebok con una mediasuela Zig y un sutil logo Vector. La espuma de EVA aporta amortiguación reactiva en cada paso. El sistema de cordones elástico permite ponerlos con rapidez cuando es momento de salir de casa.',
      images: [
        'zig_dynamica_3_alt_girls_01.jpg',
        'zig_dynamica_3_alt_girls_02.jpg',
        'zig_dynamica_3_alt_girls_03.jpg',
      ],
      inStock: 211,
      price: 64.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'zig_dynamica_3_alt_girls',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Zig Dynamica 3 Alt',
      gender: 'girls',
    },
    {
      description:
        '¿Perderse entre la multitud o destacarse del montón? La elección es suya con estos tenis Reebok para niños. Los detalles de camuflaje le imprimen nueva dimensión al diseño clásico de franjas laterales. La suela de caucho ofrece durabilidad para pasar del parque a jugar videojuegos, sin perderse ni un segundo de diversión.',
      images: [
        'royal_classic_jogger_3_boys_01.jpg',
        'royal_classic_jogger_3_boys_02.jpg',
        'royal_classic_jogger_3_boys_03.jpg',
      ],
      inStock: 189,
      price: 54.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'royal_classic_jogger_3_boys',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Royal Classic Jogger 3',
      gender: 'boys',
    },
    {
      description:
        'Maximiza el estilo deportivo de tu peque con este modelo monocromático con un look minimalista. Están disponibles en colores clásicos, blanco y negro. Su suela resistente al desgaste podrá acompañarlo adonde quiera.',
      images: [
        'reebok_royal_prime_2_boys_01.jpg',
        'reebok_royal_prime_2_boys_02.jpg',
        'reebok_royal_prime_2_boys_03.jpg',
      ],
      inStock: 200,
      price: 47.45,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'reebok_royal_prime_2_boys',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Reebok Royal Prime 2',
      gender: 'boys',
    },
    {
      description:
        'No importa a dónde vaya, tu peque se sentirá ágil siempre con estos tenis Reebok para niños. La capellada de malla transpirable mantiene sus pies cómodos todo el día. La espuma de EVA le brinda la amortiguación que necesita para correr, saltar y jugar con energía.',
      images: [
        'flexagon_energy_3_reebok_boys_01.jpg',
        'flexagon_energy_3_reebok_boys_02.jpg',
        'flexagon_energy_3_reebok_boys_03.jpg',
      ],
      inStock: 105,
      price: 64.95,
      sizes: [
        '10.5k',
        '11k',
        '11.5k',
        '12k',
        '12.5k',
        '13k',
        '13.5k',
        '1',
        '1.5',
        '2',
        '2.5',
        '3',
      ],
      slug: 'flexagon_energy_3_reebok_boys',
      type: 'shoes',
      tags: ['sneakers'],
      title: 'Flexagon Energy 3',
      gender: 'boys',
    },
  ],
};
